replicaCount: 1
image:
  repository: harbor.pintobean.xyz/aspenmesh-demo-site/paymentservice
  pullPolicy: Always
  tag: "0.1.0"
namespace: "payments"
nameOverride: "paymentservice"
fullnameOverride: "paymentservice"
containerPort: 50051
container:
  name: "server"
serviceAccount:
  create: false
  annotations: {}
  name: ""
livenessProbe:
  initialDelay: 5
  period: 5
  command: ["/bin/grpc_health_probe", "-addr=:50051"]
readinessProbe:
  initialDelay: 5
  period: 5
  command: ["/bin/grpc_health_probe", "-addr=:50051"]
env:
- name: PORT
  value: "50051"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"
- name: DISABLE_DEBUGGER
  value: "1"
resources: 
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
service:
  type: ClusterIP
  port: 50051
  targetPort: 50051
  name: grpc