namespace: "otel"
serviceAccount: 
  name: otel-sa
clusterRole:
  name: otel-role
clusterRoleBinding:
  name: otel-role-binding
otelcollector:
  replicaCount: 1
  image:
    repository: otel/opentelemetry-collector-contrib
    pullPolicy: Always
    tag: "0.50.0"
  nameOverride: "opentelemetrycollector"
  fullnameOverride: "opentelemetrycollector"
  containerPort: 4317
  container:
    name: "otel-collector"
    args:
    - --config=/conf/collector.yaml
    volumeMounts:
    - mountPath: /conf
      name: collector-config
  volumes:
  - name: collector-config
    configMap:
      name: collector-config
      items:
      - key: collector.yaml
        path: collector.yaml
  service:
    type: ClusterIP
    port: 4317
    targetPort: 4317
    name: grpc-otlp
    protocol: TCP
otelagent:
  replicaCount: 1
  image:
    repository: otel/opentelemetry-collector-contrib
    pullPolicy: Always
    tag: "0.50.0"
  nameOverride: "opentelemetryagent"
  fullnameOverride: "opentelemetryagent"
  ports: 
  - containerPort: 4317
  - containerPort: 8888
  container:
    name: "otel-collector"
    command:
      - "/otelcol"
      - "--config=/conf/agent.yaml"
    volumeMounts:
    - name: agent-config
      mountPath: /conf
  volumes:
    - name: agent-config
      configMap:
        name: agent-config
        items:
          - key: agent.yaml
            path: agent.yaml
  service:
    type: ClusterIP
    port: 4317
    targetPort: 4317
    name: grpc-otlp
    protocol: TCP
