replicaCount: 1
image:
  repository: redis
  pullPolicy: Always
  tag: "alpine"
namespace: "shopping-cart"
nameOverride: "redis-cart"
fullnameOverride: "redis-cart"
containerPort: 6379
container:
  name: "redis"
serviceAccount:
  create: false
  annotations: {}
  name: ""
livenessProbe:
  initialDelay: 5
  period: 5
  tcpSocket:
    port: 6379
readinessProbe:
  initialDelay: 5
  period: 5
  tcpSocket:
    port: 6379
resources: 
  requests:
    cpu: 70m
    memory: 200Mi
  limits:
    cpu: 125m
    memory: 256Mi
volumeMounts:
- mountPath: /data
  name: redis-data
volumes:
- name: redis-data
  emptyDir: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
service:
  type: ClusterIP
  port: 6379
  targetPort: 6379
  name: redis