---
kind: Namespace
apiVersion: v1
metadata:
  name: frontend
  labels:
    name: frontend
---
kind: Namespace
apiVersion: v1
metadata:
  name: product-catalog
  labels:
    name: product-catalog
---
kind: Namespace
apiVersion: v1
metadata:
  name: recommendations
  labels:
    name: recommendations
---
kind: Namespace
apiVersion: v1
metadata:
  name: fulfillment
  labels:
    name: fulfillment
---
kind: Namespace
apiVersion: v1
metadata:
  name: ad-engine
  labels:
    name: ad-engine
---
kind: Namespace
apiVersion: v1
metadata:
  name: payments
  labels:
    name: payments
---
kind: Namespace
apiVersion: v1
metadata:
  name: checkout
  labels:
    name: checkout
---
kind: Namespace
apiVersion: v1
metadata:
  name: shopping-cart
  labels:
    name: shopping-cart
---