adservice:
  enabled: true
boutiquedb:
  enabled: true
cartservice:
  enabled: true
checkoutservice:
  enabled: true
currencyservice:
  enabled: true
emailservice:
  enabled: true
frontend:
  enabled: true
paymentservice:
  enabled: true
productcatalogservice:
  enabled: true
recommendationservice:
  enabled: true
redis:
  enabled: true
shippingservice:
  enabled: true
