apiVersion: v1
kind: Service
metadata:
  name: {{ include "recommendationservice.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "recommendationservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol}}
      name: {{ .Values.service.name }}
  selector:
    {{- include "recommendationservice.selectorLabels" . | nindent 4 }}

