replicaCount: 1
image:
  repository: harbor.pintobean.xyz/aspenmesh-demo-site/checkoutservice
  pullPolicy: Always
  tag: "0.1.0"
namespace: "checkout"
nameOverride: "checkoutservice"
fullnameOverride: "checkoutservice"
containerPort: 5050
container:
  name: "server"
serviceAccount:
  create: false
  annotations: {}
  name: ""
livenessProbe:
  initialDelay: 15
  period: 10
  command: ["/bin/grpc_health_probe", "-addr=:5050"]
readinessProbe:
  initialDelay: 20
  period: 15
  command: ["/bin/grpc_health_probe", "-addr=:5050"]
env:
- name: PORT
  value: "5050"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice.product-catalog:3550"
- name: SHIPPING_SERVICE_ADDR
  value: "shippingservice.fulfillment:50051"
- name: PAYMENT_SERVICE_ADDR
  value: "paymentservice.payments:50051"
- name: EMAIL_SERVICE_ADDR
  value: "emailservice.fulfillment:5000"
- name: CURRENCY_SERVICE_ADDR
  value: "currencyservice.payments:7000"
- name: CART_SERVICE_ADDR
  value: "cartservice.shopping-cart:7070"
- name: DISABLE_STATS
  value: "1"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"
resources: 
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
service:
  type: ClusterIP
  port: 5050
  targetPort: 5050
  name: grpc