replicaCount: 1
image:
  repository: harbor.pintobean.xyz/aspenmesh-demo-site/adservice
  pullPolicy: Always
  tag: "0.1.0"
namespace: "ad-engine"
nameOverride: "adservice"
fullnameOverride: "adservice"
containerPort: 9555
container:
  name: "server"
serviceAccount:
  create: false
  annotations: {}
  name: ""
livenessProbe:
  initialDelay: 20
  period: 15
  command: ["/bin/grpc_health_probe", "-addr=:9555"]
readinessProbe:
  initialDelay: 20
  period: 15
  command: ["/bin/grpc_health_probe", "-addr=:9555"]
service:
  type: ClusterIP
  port: 9555
  targetPort: 9555
  name: grpc
env:
- name: PORT
  value: "9555"
- name: DISABLE_STATS
  value: "1"
- name: DISABLE_TRACING
  value: "1"
resources: 
  requests:
    cpu: 200m
    memory: 180Mi
  limits:
    cpu: 300m
    memory: 300Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
