replicaCount: 1
image:
  repository: harbor.pintobean.xyz/aspenmesh-demo-site/productcatalogservice
  pullPolicy: Always
  tag: "0.1.0"
namespace: "product-catalog"
nameOverride: "productcatalogservice"
fullnameOverride: "productcatalogservice"
containerPort: 3550
container:
  name: "server"
serviceAccount:
  create: false
  annotations: {}
  name: ""
livenessProbe:
  initialDelay: 5
  period: 5
  command: ["/bin/grpc_health_probe", "-addr=:3550"]
readinessProbe:
  initialDelay: 5
  period: 5
  command: ["/bin/grpc_health_probe", "-addr=:3550"]
env:
- name: PORT
  value: "3550"
- name: DISABLE_STATS
  value: "1"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"
- name: PG_HOST
  value: "boutiquedb.product-catalog.svc"
- name: PG_PORT
  value: "5432"
- name: PG_USERNAME
  value: "postgres"
- name: PG_PASSWORD
  value: "postgres"
- name: PG_DATABASE
  value: "boutique"
resources: 
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
service:
  type: ClusterIP
  port: 3550
  targetPort: 3550
  name: grpc